# Jekyll Defaults
title: Tmax.AI
description: Tmax AI technical blog.
# baseurl: "https://tmaxai.github.io" # the subpath of your site, e.g. /blog
baseurl: ""
timezone: Asia/Seoul
locale: "ko-KR"

owner:
  name: tmaxdata

url: "https://tmaxai.github.io"
github: https://tmaxai.github.io/
highlighter: rouge
excerpt_separator: "<!-- more -->"
markdown: kramdown
permalink: /post/:title/
paginate: 5
plugins: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
favicon: icon.png
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Categories
  url: /categories/
- text: Tags
  url: /tags/

mathjax: true

sass:
    sass_dir: css
    style: :compressed

disqus: https-tmaxai-github-io
